version: "3"
services:


  #MySQL Database 
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./sql/accounts.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=patipansixth
      - MYSQL_PASSWORD=sixth
      - MYSQL_ROOT_PASSWORD=sixth
    networks:
      - internalnetworks


  #Node.js Web app
  node:
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=patipansixth
      - DB_PASSWORD=sixth
      - DB_NAME=accounts
    depends_on:
      - mysqldb
    networks:
      - internalnetworks



  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    expose:
      - 8000
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=sixth
    depends_on:
      - mysqldb
    networks:
      - internalnetworks


      
networks:
  internalnetworks:
    driver: bridge